import { execFileSync } from 'node:child_process';

export function branchName(courseSlug: string): string {
  return `harvest/${courseSlug}`;
}

export interface PrOffering {
  year: number;
  term: string;
  confidence: number;
  flaggedFields: string[];
  droppedFields: string[];
  source: 'official' | 'wayback';
  sourceUrl: string;
}

export interface PrBodyInput {
  courseSlug: string;
  offerings: PrOffering[];
  tags: string[];
}

export function buildPrBody(input: PrBodyInput): string {
  const lines: string[] = [];
  lines.push(`## Harvested: ${input.courseSlug}`, '');
  lines.push(`**Tags:** ${input.tags.join(', ') || '_none_'}`, '');
  lines.push('| Offering | Confidence | Source | Flagged | Dropped |');
  lines.push('|---|---|---|---|---|');
  for (const o of input.offerings) {
    lines.push(
      `| ${o.year} ${o.term} | ${o.confidence.toFixed(2)} | [${o.source}](${o.sourceUrl}) | ` +
      `${o.flaggedFields.join(', ') || '—'} | ${o.droppedFields.join(', ') || '—'} |`,
    );
  }
  lines.push('', '_Generated by the onboard-course harvester. Review flagged/dropped fields against the source links above._');
  return lines.join('\n');
}

// Thin exec wrapper — not unit-tested (shells out to git/gh).
export function openPr(opts: { branch: string; title: string; body: string; files: string[]; baseBranch?: string }): void {
  execFileSync('git', ['checkout', '-b', opts.branch]);
  execFileSync('git', ['add', ...opts.files]);
  execFileSync('git', ['commit', '-m', opts.title]);
  execFileSync('git', ['push', '-u', 'origin', opts.branch]);
  const baseArgs = opts.baseBranch ? ['--base', opts.baseBranch] : [];
  execFileSync('gh', ['pr', 'create', '--title', opts.title, '--body', opts.body, ...baseArgs]);
}
